#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
VALIDATOR="$SCRIPT_DIR/validate-update-manifest.sh"
GENERATOR="$SCRIPT_DIR/generate-update-manifest.sh"
CHECK_UPDATE="$SCRIPT_DIR/check-update.sh"

TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "ERROR: required command not found: $1" >&2
    exit 1
  }
}

assert_fails() {
  local description="$1"
  shift
  if "$@" >/dev/null 2>&1; then
    echo "FAIL: $description (should fail)" >&2
    exit 1
  fi
  echo "PASS: $description"
}

require_cmd jq
require_cmd openssl
require_cmd base64
require_cmd sha256sum

BASE_URL="file://$PROJECT_ROOT/INSTALADOR/saida"
VALID_MANIFEST="$TMP_DIR/valid.json"

# 1) Manifesto valido gerado pelo script.
"$GENERATOR" --base-url "$BASE_URL" --output "$VALID_MANIFEST" --channel stable --rollout-percent 25 --signature "UNSIGNED"
"$VALIDATOR" --manifest "$VALID_MANIFEST"
echo "PASS: valid manifest generated by generator"

# 2) Casos negativos de schema/contrato.
INVALID_MISSING="$TMP_DIR/missing-field.json"
jq 'del(.artifacts)' "$VALID_MANIFEST" > "$INVALID_MISSING"
assert_fails "missing required field rejected" "$VALIDATOR" --manifest "$INVALID_MISSING"

INVALID_HASH="$TMP_DIR/bad-hash.json"
jq '.artifacts[0].sha256 = "xyz"' "$VALID_MANIFEST" > "$INVALID_HASH"
assert_fails "invalid sha256 rejected" "$VALIDATOR" --manifest "$INVALID_HASH"

INVALID_SIG_TYPE="$TMP_DIR/bad-signature-type.json"
jq '.artifacts[0].signature = 123' "$VALID_MANIFEST" > "$INVALID_SIG_TYPE"
assert_fails "non-string signature rejected" "$VALIDATOR" --manifest "$INVALID_SIG_TYPE"

INVALID_CHANNEL="$TMP_DIR/bad-channel.json"
jq '.channel = "prod"' "$VALID_MANIFEST" > "$INVALID_CHANNEL"
assert_fails "invalid channel rejected" "$VALIDATOR" --manifest "$INVALID_CHANNEL"

INVALID_DATE="$TMP_DIR/bad-date.json"
jq '.published_at_utc = "not-a-date"' "$VALID_MANIFEST" > "$INVALID_DATE"
assert_fails "invalid published_at_utc rejected" "$VALIDATOR" --manifest "$INVALID_DATE"

INVALID_RELEASE_NOTES_URL="$TMP_DIR/bad-release-notes-url.json"
jq '.release_notes_url = "release-notes/v1.0.0"' "$VALID_MANIFEST" > "$INVALID_RELEASE_NOTES_URL"
assert_fails "relative release_notes_url rejected" "$VALIDATOR" --manifest "$INVALID_RELEASE_NOTES_URL"

INVALID_URL_REL="$TMP_DIR/bad-relative-url.json"
jq '.artifacts[0].url = "Protons-1.0.0-x64.msi"' "$VALID_MANIFEST" > "$INVALID_URL_REL"
assert_fails "relative artifact url rejected" "$VALIDATOR" --manifest "$INVALID_URL_REL"

INVALID_SIG_REL="$TMP_DIR/bad-relative-signature-url.json"
jq '.artifacts[0].signature = "artifact.sig"' "$VALID_MANIFEST" > "$INVALID_SIG_REL"
assert_fails "relative signature url rejected" "$VALIDATOR" --manifest "$INVALID_SIG_REL"

assert_fails "strict mode rejects UNSIGNED" "$VALIDATOR" --manifest "$VALID_MANIFEST" --strict-signature

# 3) Caso positivo com assinatura criptografica valida e check-update estrito.
ARTIFACT_FILE="$TMP_DIR/protons-test-artifact.bin"
SIG_FILE_RAW="$TMP_DIR/protons-test-artifact.bin.sig.raw"
SIG_FILE_B64="$TMP_DIR/protons-test-artifact.bin.sig"
PRIV_KEY="$TMP_DIR/private.pem"
PUB_KEY="$TMP_DIR/public.pem"

printf 'protons-update-test-%s\n' "$(date -u +%s)" > "$ARTIFACT_FILE"
ART_SHA="$(sha256sum "$ARTIFACT_FILE" | awk '{print $1}')"
ART_SIZE="$(stat -c '%s' "$ARTIFACT_FILE")"

openssl genpkey -algorithm RSA -out "$PRIV_KEY" -pkeyopt rsa_keygen_bits:2048 >/dev/null 2>&1
openssl pkey -in "$PRIV_KEY" -pubout -out "$PUB_KEY" >/dev/null 2>&1
openssl dgst -sha256 -sign "$PRIV_KEY" -out "$SIG_FILE_RAW" "$ARTIFACT_FILE"
base64 < "$SIG_FILE_RAW" | tr -d '\n' > "$SIG_FILE_B64"

SIGNED_MANIFEST="$TMP_DIR/signed-valid.json"
NOW_UTC="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

jq -n \
  --arg version "9.9.9" \
  --arg channel "stable" \
  --arg published_at_utc "$NOW_UTC" \
  --arg min_supported_version "1.0.0" \
  --arg release_notes_url "https://example.com/release-notes/9.9.9" \
  --arg artifact_url "file://$ARTIFACT_FILE" \
  --arg artifact_sha "$ART_SHA" \
  --arg artifact_sig "file://$SIG_FILE_B64" \
  --argjson artifact_size "$ART_SIZE" \
  '{
    version: $version,
    channel: $channel,
    published_at_utc: $published_at_utc,
    min_supported_version: $min_supported_version,
    release_notes_url: $release_notes_url,
    rollout_percent: 100,
    artifacts: [
      {
        platform: "linux",
        type: "appimage",
        url: $artifact_url,
        sha256: $artifact_sha,
        size_bytes: $artifact_size,
        signature: $artifact_sig
      }
    ]
  }' > "$SIGNED_MANIFEST"

"$VALIDATOR" --manifest "$SIGNED_MANIFEST" --strict-signature
echo "PASS: strict validator accepted signed manifest"

"$CHECK_UPDATE" --manifest "$SIGNED_MANIFEST" --platform linux --type appimage --require-signature --public-key "$PUB_KEY" --download-dir "$TMP_DIR/downloads" >/dev/null
echo "PASS: check-update strict mode accepted valid signature"

# 4) Check-update estrito deve falhar para assinatura invalida/ausente.
SIGNED_BAD_SIG="$TMP_DIR/signed-bad-signature.json"
jq '.artifacts[0].signature = "file:///tmp/nonexistent.sig"' "$SIGNED_MANIFEST" > "$SIGNED_BAD_SIG"
assert_fails "check-update fails with invalid signature reference" "$CHECK_UPDATE" --manifest "$SIGNED_BAD_SIG" --platform linux --type appimage --require-signature --public-key "$PUB_KEY" --download-dir "$TMP_DIR/downloads-bad"

UNSIGNED_STRICT="$TMP_DIR/unsigned-strict.json"
jq '.artifacts[0].signature = "UNSIGNED"' "$SIGNED_MANIFEST" > "$UNSIGNED_STRICT"
assert_fails "check-update strict rejects UNSIGNED" "$CHECK_UPDATE" --manifest "$UNSIGNED_STRICT" --platform linux --type appimage --require-signature --public-key "$PUB_KEY" --download-dir "$TMP_DIR/downloads-unsigned"

# 5) Cenarios de pinning de chave publica (RODADA3-20260215)
# Cenario: manifesto com chave publica diferente deve falhar
WRONG_PRIV_KEY="$TMP_DIR/wrong-private.pem"
WRONG_PUB_KEY="$TMP_DIR/wrong-public.pem"
WRONG_SIG_FILE_RAW="$TMP_DIR/wrong-artifact.sig.raw"
WRONG_SIG_FILE_B64="$TMP_DIR/wrong-artifact.sig"

openssl genpkey -algorithm RSA -out "$WRONG_PRIV_KEY" -pkeyopt rsa_keygen_bits:2048 >/dev/null 2>&1
openssl pkey -in "$WRONG_PRIV_KEY" -pubout -out "$WRONG_PUB_KEY" >/dev/null 2>&1
openssl dgst -sha256 -sign "$WRONG_PRIV_KEY" -out "$WRONG_SIG_FILE_RAW" "$ARTIFACT_FILE"
base64 < "$WRONG_SIG_FILE_RAW" | tr -d '\n' > "$WRONG_SIG_FILE_B64"

WRONG_KEY_MANIFEST="$TMP_DIR/wrong-key-manifest.json"
jq --arg wrong_sig "file://$WRONG_SIG_FILE_B64" '.artifacts[0].signature = $wrong_sig' "$SIGNED_MANIFEST" > "$WRONG_KEY_MANIFEST"

assert_fails "check-update rejects manifest signed with different key" "$CHECK_UPDATE" --manifest "$WRONG_KEY_MANIFEST" --platform linux --type appimage --require-signature --public-key "$PUB_KEY" --download-dir "$TMP_DIR/downloads-wrong-key"
echo "PASS: pinning de chave publica bloqueia assinatura de chave diferente"

# Cenario: manifesto sem assinatura em modo strict deve falhar
UNSIGNED_PINNING="$TMP_DIR/unsigned-pinning.json"
jq '.artifacts[0].signature = "UNSIGNED"' "$SIGNED_MANIFEST" > "$UNSIGNED_PINNING"
assert_fails "check-update fails on unsigned with key pinning" "$CHECK_UPDATE" --manifest "$UNSIGNED_PINNING" --platform linux --type appimage --require-signature --public-key "$PUB_KEY" --download-dir "$TMP_DIR/downloads-unsigned-pinning"
echo "PASS: pinning de chave publica bloqueia manifesto sem assinatura"

# Cenario: chave publica incorreta fornecida (public key mismatch)
assert_fails "check-update fails with wrong public key provided" "$CHECK_UPDATE" --manifest "$SIGNED_MANIFEST" --platform linux --type appimage --require-signature --public-key "$WRONG_PUB_KEY" --download-dir "$TMP_DIR/downloads-key-mismatch"
echo "PASS: pinning detecta incompatibilidade de chave publica"

# Cenario: versao regressiva nao deve acionar update.
REGRESSIVE_MANIFEST="$TMP_DIR/regressive-version.json"
jq '.version = "0.0.1"' "$SIGNED_MANIFEST" > "$REGRESSIVE_MANIFEST"
if "$CHECK_UPDATE" --manifest "$REGRESSIVE_MANIFEST" --platform linux --type appimage --require-signature --public-key "$PUB_KEY" --download-dir "$TMP_DIR/downloads-regressive" | rg -q "No update required"; then
  echo "PASS: regressive version does not trigger update"
else
  echo "FAIL: regressive version should not trigger update" >&2
  exit 1
fi

echo "All update-manifest tests passed (including key pinning scenarios)."
